### ISSUE TITLE
vscode buttons

### ISSUE THREAD

**Issue by eugenekim-orrum** [datacoves/docs#1]
Add documentation to explanations/best-practices/datacoves/folder-structure.md for vscode buttons
.vscode/settings.json for current user
transform/.vscode/settings.json for team

**Comment by noel** [comment]
@mayrapena1324 this is what we need to cover in getting started page for developer

**Comment by mayrapena1324** [comment]
Added: 
https://docs.datacoves.com/#/how-tos/vscode/override?id=how-to-customize-the-status-bar
https://docs.datacoves.com/#/explanation/best-practices/datacoves/folder-structure?id=vscodesettingsjson
